### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by semoac** [ybhatnagar/kube-tetris#7]
Hi.

Can you add a little guide on how to build and install this?

Thanks

**Comment by ybhatnagar** [comment]
Makes Sense. Readme really needs more information. I will pick it up.

**Comment by yangyongzhi7** [comment]
This is a good tool for save the utilization of  a cluster, yes, I need some installing information to research it.

**Comment by ybhatnagar** [comment]
Please use this branch: https://github.com/ybhatnagar/kube-tetris/tree/use_kubernetes_client
